version: "3.7"

services:
  kubealived:
    image: gurken2108/kubealived:latest
    restart: unless-stopped
    network_mode: host
    environment:
      KEEPALIVE_STATE: "MASTER"
      KEEPALIVE_INTERFACE: "eth0"
      KEEPALIVE_IPADDRESS: "192.168.50.100"
    cap_add:
      - NET_ADMIN
    # alternatively use custom config file by mounting it
    #volumes:
    #  - ./keepalive.conf:/etc/keepalived/keepalived.conf