apiVersion: v1
kind: Namespace
metadata:
  name: kubealived-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubealived
  namespace: kubealived-system
  labels:
    app: kubealived
spec:
  selector:
    matchLabels:
      app: kubealived
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubealived
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      hostNetwork: true
      containers:
      - name: kubealived
        image: gurken2108/kubealived:latest
        env:
        - name: KEEPALIVE_INTERFACE
          value: "_IFACE_"
        - name: KEEPALIVE_IPADDRESS
          value: "_IP_"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
